import { Product, ServiceItem } from './types';

export const LOGO_URL = "data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%20200%2060%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccircle%20cx%3D%2225%22%20cy%3D%2230%22%20r%3D%2222%22%20stroke%3D%22black%22%20stroke-width%3D%223%22%20fill%3D%22none%22%2F%3E%3Ccircle%20cx%3D%2225%22%20cy%3D%2230%22%20r%3D%2216%22%20stroke%3D%22black%22%20stroke-width%3D%221%22%20opacity%3D%220.5%22%20fill%3D%22none%22%2F%3E%3Ctext%20x%3D%2258%22%20y%3D%2238%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-weight%3D%22900%22%20font-size%3D%2234%22%20fill%3D%22black%22%20letter-spacing%3D%22-1%22%3ESURES%3C%2Ftext%3E%3Ctext%20x%3D%2260%22%20y%3D%2252%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-weight%3D%22600%22%20font-size%3D%228%22%20fill%3D%22black%22%20letter-spacing%3D%223.5%22%3ECLIMATIZACION%3C%2Ftext%3E%3C%2Fsvg%3E";

export const COMPANY_INFO = {
  name: "Sures",
  legalName: "Hijos y Nietos de Maria Asunción Cornejo S.R.L.",
  address: "Aristóbulo del Valle 2518, Lanús Oeste, Buenos Aires",
  phone1: "11 3240-1124",
  phone2: "11 3240-1768",
  whatsapp: "5491132401768",
  email: "administracion@sures.com.ar",
  dealers: ["Carrier", "Midea"],
  website: "www.sures.com.ar"
};

export const PRODUCTS: Product[] = [
  // --- VENTANA / PORTÁTILES MIDEA ---
  {
    id: "midea-mcve09",
    name: "Midea Ventana 2250 Frío Solo",
    model: "MCVE09RE22F1",
    type: "Compacto de Ventana",
    frigorias: 2193,
    kcal: 2193,
    voltage: "220 V (50 hz)",
    power: "0,81 kW",
    refrigerant: "R-410A",
    weight: "4,7 kg",
    dimensions: "60 x 38 x 56 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Ventana",
    climateType: "Frío Solo",
    features: ["Modo Sleep", "Función Timer", "1 Año de Garantía"],
    image: "/2250 FRIO SOLO MIDEA.jpg",
    category: "residential",
  },
  {
    id: "midea-mcve12",
    name: "Midea Ventana 3000 Frío Solo",
    model: "MCVE12R8F1",
    type: "Compacto de Ventana",
    frigorias: 3000,
    kcal: 3010,
    voltage: "220 V (50 hz)",
    power: "1,14 kW",
    refrigerant: "R-410A",
    weight: "37 kg",
    dimensions: "60 x 38 x 56 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Ventana",
    climateType: "Frío Solo",
    features: ["Modo Sleep", "Función Timer", "1 Año de Garantía"],
    image: "/2250 FRIO SOLO MIDEA.jpg",
    category: "residential",
  },
  {
    id: "midea-mcve18",
    name: "Midea Ventana 4500 Frío Solo",
    model: "MCVE18RE22F1",
    type: "Compacto de Ventana",
    frigorias: 4438,
    kcal: 4438,
    voltage: "220 V (50 hz)",
    power: "1,66 kW",
    refrigerant: "R-410A",
    weight: "53 kg",
    dimensions: "68 x 42,8 x 66 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Ventana",
    climateType: "Frío Solo",
    features: ["Modo Sleep", "Función Timer", "1 Año de Garantía"],
    image: "/2250 FRIO SOLO MIDEA.jpg",
    category: "residential",
  },

  // --- PISO TECHO CARRIER ELITE (Tradicional) ---
  {
    id: "carrier-elite-3tr-mono",
    name: "Carrier Elite 3TR Monofásico",
    model: "53KMQ036HP-701A",
    type: "Piso Techo",
    frigorias: 9000,
    kcal: 9000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 30kg / Cond: 80kg",
    dimensions: "Int: 128,5 x 23,5 x 67,5 cm | Ext: 94,6 x 81 x 41 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    hasDehumidifier: true,
    placement: "Piso Techo",
    climateType: "Frío/Calor",
    features: [
      "Compresor Scroll Alta Eficiencia",
      "Diseño Moderno",
      "3 Años de Garantía",
      "Condensadora Descarga Vertical",
      "Control Remoto LCD",
      "Toma de Aire Exterior (opcional)",
    ],
    image: "/3 TR MONOFASICO FRIO CALOR ELITE.jpg",
    category: "residential",
  },
  {
    id: "carrier-elite-3tr-tri",
    name: "Carrier Elite 3TR Trifásico",
    model: "53KMQ036HP-901A",
    type: "Piso Techo",
    frigorias: 9000,
    kcal: 9000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 30kg / Cond: 77kg",
    dimensions: "Int: 128,5 x 23,5 x 67,5 cm | Ext: 94,6 x 81 x 41 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    hasDehumidifier: true,
    placement: "Piso Techo",
    climateType: "Frío/Calor",
    features: [
      "Trifásico",
      "Compresor Scroll Alta Eficiencia",
      "3 Años de Garantía",
      "Control Remoto LCD",
      "Presostatos Alta/Baja Presión",
      "Detector Secuencia y Falta de Fase",
    ],
    image: "/3 TR TRIFASICO FRIO CALOR ELITE.jpg",
    category: "residential",
  },
  {
    id: "carrier-elite-5tr",
    name: "Carrier Elite 5TR Trifásico",
    model: "53VBQ057HP-902A",
    type: "Piso Techo",
    frigorias: 15000,
    kcal: 15000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 31kg / Cond: 80kg",
    dimensions: "Int: 128,5 x 23,5 x 41 cm | Ext: 94,6 x 81 x 67,5 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    hasDehumidifier: true,
    placement: "Piso Techo",
    climateType: "Frío/Calor",
    features: [
      "Inverter",
      "Wi-Fi Integrado",
      "Trifásico",
      "3 Años de Garantía",
      "Control Remoto LCD",
    ],
    image: "/5 TR TRIFASICO FRIO CALOR ELITE.png",
    category: "commercial",
  },
  {
    id: "carrier-elite-6tr",
    name: "Carrier Elite 6TR Trifásico",
    model: "53LMQ072HP-901A",
    type: "Piso Techo",
    frigorias: 18000,
    kcal: 18000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 39kg / Cond: 97kg",
    dimensions: "Int: 165 x 23,5 x 67,5 cm | Ext: 90 x 117 x 35 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    hasDehumidifier: true,
    placement: "Piso Techo",
    climateType: "Frío/Calor",
    features: [
      "Alta Capacidad",
      "Trifásico",
      "3 Años de Garantía",
      "Control Remoto LCD",
      "Presostatos Alta/Baja Presión",
    ],
    image: "/6 TR TRIFASICO FRIO CALOR ELITE.webp",
    category: "commercial",
  },

  // --- PISO TECHO CARRIER ELITE INVERTER ---
  {
    id: "carrier-elite-inv-3tr",
    name: "Carrier Elite Inverter 3TR",
    model: "53VRQ036HP-701A",
    type: "Piso Techo",
    frigorias: 9000,
    kcal: 9000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 40kg / Cond: 67kg",
    dimensions: "Int: 165 x 23,5 x 67,5 cm | Ext: 94,6 x 81 x 41 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: true,
    hasWifi: false,
    hasTimer: true,
    hasDehumidifier: true,
    placement: "Piso Techo",
    climateType: "Frío/Calor",
    features: [
      "Inverter",
      "Refrigerante Ecológico R410A",
      "Súper Silencioso",
      "3 Años de Garantía",
      "Condensadora Descarga Horizontal",
      "Control Remoto LCD",
    ],
    image: "/3 TR TRIFASICO FRIO CALOR ELITE INVERTER.jpg",
    category: "residential",
  },
  {
    id: "carrier-elite-inv-5tr-r32",
    name: "Carrier Elite Inverter 5TR R-32",
    model: "53VBQ057HP-902A",
    type: "Piso Techo",
    frigorias: 15000,
    kcal: 15000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-32",
    weight: "Evap: 42kg / Cond: 76,1kg",
    dimensions: "Int: 165 x 23,5 x 41 cm | Ext: 94,6 x 81 x 67,5 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    hasDehumidifier: true,
    placement: "Piso Techo",
    climateType: "Frío/Calor",
    features: [
      "Gas R-32 Ecológico",
      "Inverter",
      "Wi-Fi Integrado",
      "3 Años de Garantía",
      "Control Remoto LCD",
    ],
    image: "/5 TR TRIFASICO FRIO CALOR ELITE INVERTER R-32.png",
    category: "commercial",
  },
  {
    id: "carrier-elite-inv-6tr-r32",
    name: "Carrier Elite Inverter 6TR R-32",
    model: "53VBQ072HP-902A",
    type: "Piso Techo",
    frigorias: 18000,
    kcal: 18000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-32",
    weight: "Evap: 42kg / Cond: 85,6kg",
    dimensions: "Int: 165 x 23,5 x 37,5 cm | Ext: 98 x 97,5 x 67,5 cm",
    color: "Blanco",
    efficiency: "B",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    hasDehumidifier: true,
    placement: "Piso Techo",
    climateType: "Frío/Calor",
    features: [
      "Gas R-32 Ecológico",
      "Inverter",
      "Wi-Fi Integrado",
      "3 Años de Garantía",
      "Control Remoto LCD",
      "Condensadora Descarga Horizontal",
    ],
    image: "/6 TR TRIFASICO FRIO CALOR ELITE INVERTER R-32.png",
    category: "commercial",
  },

  // --- MIDEA PISO TECHO / PARED ---
  {
    id: "midea-8750-inv",
    name: "Midea Inverter Smart 8750",
    model: "MSAGIC-30H-N10M",
    type: "Piso Techo",
    frigorias: 9000,
    kcal: 8394,
    voltage: "220 V",
    current: "Refrig: 15,21 A / Calef: 15 A",
    refrigerant: "R-410A",
    weight: "Evap: 17,7kg / Cond: 48kg",
    dimensions: "Int: 125,9 x 36,2 x 34,2 cm | Ext: 67,3 x 89 x 28,3 cm",
    color: "Blanco",
    efficiency: "C (Frío) / D (Calor)",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Techo / Pared",
    climateType: "Frío/Calor",
    features: [
      "Inverter - Ahorro 35% Energía",
      "Compatible Google Home y Alexa",
      "Control por Voz",
      "Recubrimiento Dorado (Gold Cover)",
      "Función Gear (50%, 75%, 100%)",
      "Auto-limpieza",
      "App Smartphone/Tablet",
    ],
    image: "/8750 FRIO CALOR MIDEA INVERTER.jpg",
    category: "residential",
  },

  // --- SPLIT CARRIER XPOWER INVERTER R32 ---
  {
    id: "carrier-split-2250-r32",
    name: "Carrier XPower Inverter 2250 R-32",
    model: "53XPC09C5",
    type: "Split",
    frigorias: 2356,
    kcal: 2492,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Gas R-32 Ecológico", "Inverter - Ahorro 35%", "Wi-Fi / App", "Alexa / Google Home", "Función Gear", "Silver Ion Filter"],
    image: "/2250 FRIO CALOR XPOWER INVERTER R-32.webp",
    category: "residential",
  },
  {
    id: "carrier-split-3000-r32",
    name: "Carrier XPower Inverter 3000 R-32",
    model: "53XPC12C5",
    type: "Split",
    frigorias: 3096,
    kcal: 2993,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Gas R-32 Ecológico", "Inverter - Ahorro 35%", "Wi-Fi / App", "Follow Me", "Función Gear", "Silver Ion Filter"],
    image: "/3000 FRIO CALOR XPOWER INVERTER R-32.png",
    category: "residential",
  },
  {
    id: "carrier-split-4500-r32",
    name: "Carrier XPower Inverter 4500 R-32",
    model: "53XPC18C5",
    type: "Split",
    frigorias: 4601,
    kcal: 4420,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Gas R-32 Ecológico", "Inverter - Ahorro 35%", "Wi-Fi / App", "Alexa / Google Home", "Función Gear", "Silver Ion Filter"],
    image: "/3000 FRIO CALOR XPOWER INVERTER R-32.png",
    category: "residential",
  },
  {
    id: "carrier-split-5500-r32",
    name: "Carrier XPower Inverter 5500 R-32",
    model: "53XPC22C5",
    type: "Split",
    frigorias: 5590,
    kcal: 5796,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Gas R-32 Ecológico", "Inverter - Ahorro 35%", "Wi-Fi / App", "Alta Potencia", "Función Gear", "Silver Ion Filter"],
    image: "/3000 FRIO CALOR XPOWER INVERTER R-32.png",
    category: "residential",
  },

  // --- SPLIT MIDEA STANDARD ---
  {
    id: "midea-split-2250",
    name: "Midea Standard 2250",
    model: "MSAFC-09H-01F",
    type: "Split",
    frigorias: 2348,
    kcal: 2245,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    efficiency: "A",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Led Display", "Recubrimiento Dorado (Gold Cover)", "Modo Reposo", "1 Año de Garantía"],
    image: "/2250 FRIO CALOR MIDEA.png",
    category: "residential",
  },
  {
    id: "midea-split-3000",
    name: "Midea Standard 3000",
    model: "MSAFC-12H-01F",
    type: "Split",
    frigorias: 2950,
    kcal: 2666,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    efficiency: "A",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Led Display", "Recubrimiento Dorado (Gold Cover)", "Auto-limpieza", "1 Año de Garantía"],
    image: "/3000 FRIO CALOR MIDEA.png",
    category: "residential",
  },
  {
    id: "midea-split-4300",
    name: "Midea Standard 4300",
    model: "MSAFC-18H-01F",
    type: "Split",
    frigorias: 4420,
    kcal: 4162,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    efficiency: "B",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Led Display", "Recubrimiento Dorado (Gold Cover)", "Alta Capacidad", "1 Año de Garantía"],
    image: "/4300 FRIO CALOR MIDEA.png",
    category: "residential",
  },
  {
    id: "midea-split-5400",
    name: "Midea Standard 5400",
    model: "MSAFC-22H-01F",
    type: "Split",
    frigorias: 5607,
    kcal: 5400,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    efficiency: "B",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Led Display", "Recubrimiento Dorado (Gold Cover)", "Alta Potencia", "1 Año de Garantía"],
    image: "/5400 FRIO CALOR MIDEA.png",
    category: "residential",
  },

  // --- SPLIT MIDEA INVERTER R32 ---
  {
    id: "midea-inv-r32-2250",
    name: "Midea Inverter 2250 R-32",
    model: "MSABIC-09H-01F",
    type: "Split",
    frigorias: 2356,
    kcal: 2494,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Gas R-32 Ecológico", "Inverter - Ahorro 35%", "Wi-Fi / App", "Gold Cover", "1 Año de Garantía"],
    image: "/2250 FRIO CALOR MIDEA INVERTER R-32.png",
    category: "residential",
  },
  {
    id: "midea-inv-r32-3000",
    name: "Midea Inverter 3000 R-32",
    model: "MSABIC-12H-01F",
    type: "Split",
    frigorias: 3096,
    kcal: 2958,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Gas R-32 Ecológico", "Inverter - Ahorro 35%", "Wi-Fi / App", "Gold Cover", "1 Año de Garantía"],
    image: "/3000 FRIO CALOR MIDEA INVERTER R-32.png",
    category: "residential",
  },
  {
    id: "midea-inv-r32-4500",
    name: "Midea Inverter 4500 R-32",
    model: "MSABIC-18H-01F",
    type: "Split",
    frigorias: 4601,
    kcal: 4420,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Gas R-32 Ecológico", "Inverter - Ahorro 35%", "Wi-Fi / App", "Gold Cover", "1 Año de Garantía"],
    image: "/4500 FRIO CALOR MIDEA INVERTER R-32.png",
    category: "residential",
  },
  {
    id: "midea-inv-r32-5500",
    name: "Midea Inverter 5500 R-32",
    model: "MSABIC-22H-01F",
    type: "Split",
    frigorias: 5590,
    kcal: 5796,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Gas R-32 Ecológico", "Inverter - Ahorro 35%", "Wi-Fi / App", "Gold Cover", "1 Año de Garantía"],
    image: "/5500 FRIO CALOR MIDEA INVERTER R-32.png",
    category: "residential",
  },

  // --- SPLIT MIDEA INVERTER (R410) ---
  {
    id: "midea-inv-3000",
    name: "Midea Inverter 3000",
    model: "MSAGIC-12H-N10M",
    type: "Split",
    frigorias: 2967,
    kcal: 2967,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Inverter - Ahorro 35%", "Gold Cover", "Wi-Fi / App", "Filtro Alta Densidad", "1 Año de Garantía"],
    image: "/3000 FRIO CALOR MIDEA INVERTER.png",
    category: "residential",
  },
  {
    id: "midea-inv-4500",
    name: "Midea Inverter 4500",
    model: "MSAGIC-18H-N10M",
    type: "Split",
    frigorias: 4400,
    kcal: 4400,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Inverter - Ahorro 35%", "Gold Cover", "Wi-Fi / App", "1 Año de Garantía"],
    image: "/4500 FRIO CALOR MIDEA INVERTER.png",
    category: "residential",
  },

  // --- MIDEA BREEZELESS ---
  {
    id: "midea-breeze-3000",
    name: "Midea Breezeless E 3000",
    model: "MSFAAU-12HRFN8-QRD6GW",
    type: "Split",
    frigorias: 3139,
    kcal: 3300,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Tecnología Sin Corrientes de Aire", "Inverter", "Wi-Fi / App", "7.000 Micro-orificios", "1 Año de Garantía"],
    image: "/3000 FRIO CALOR MIDEA BREEZELESS E.png",
    category: "residential",
  },
  {
    id: "midea-breeze-5500",
    name: "Midea Breezeless E 5500",
    model: "MSFAAU-18HRFN8-QRD6GW",
    type: "Split",
    frigorias: 4859,
    kcal: 5000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-32",
    color: "Blanco",
    efficiency: "A",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Pared",
    climateType: "Frío/Calor",
    features: ["Tecnología Sin Corrientes de Aire", "Inverter", "Wi-Fi / App", "Alta Eficiencia", "1 Año de Garantía"],
    image: "/5500 FRIO CALOR MIDEA BREEZELESS E.png",
    category: "residential",
  },

  // --- COMERCIAL: BAJA SILUETA TRADICIONAL ---
  {
    id: "bs-trad-1.5",
    name: "Baja Silueta 1.5TR Monofásico",
    model: "53NQHE018A-701",
    type: "Baja Silueta",
    frigorias: 4500,
    kcal: 4500,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 24kg / Cond: 36,5kg",
    dimensions: "Int: 88 x 21 x 67,5 cm | Ext: 77 x 55,5 x 30 cm",
    color: "Blanco",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Baja Silueta",
    climateType: "Frío/Calor",
    features: ["Perfil Bajo", "Bajo Ruido", "Control Alámbrico", "Frío Calor por Bomba"],
    image: "/1,5 TR FRIO CALOR MONOFASICO BAJA SILUETA TRADICIONAL.jpg",
    category: "commercial",
  },
  {
    id: "bs-trad-2",
    name: "Baja Silueta 2TR Monofásico",
    model: "53NQHE024A-701",
    type: "Baja Silueta",
    frigorias: 6000,
    kcal: 6000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 31kg / Cond: 53kg",
    dimensions: "Int: 110 x 24,9 x 77,4 cm | Ext: 84,5 x 70,2 x 36,3 cm",
    color: "Blanco",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Baja Silueta",
    climateType: "Frío/Calor",
    features: ["Perfil Bajo", "Bajo Ruido", "Frío Calor por Bomba"],
    image: "/2 TR FRIO CALOR MONOFASICO BAJA SILUETA TRADICIONAL.jpg",
    category: "commercial",
  },
  {
    id: "bs-trad-3",
    name: "Baja Silueta 3TR Monofásico",
    model: "53NQHE036A-701",
    type: "Baja Silueta",
    frigorias: 9000,
    kcal: 9000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 32kg / Cond: 74,5kg",
    dimensions: "Int: 111 x 24,9 x 77,4 cm | Ext: 94,6 x 81 x 41 cm",
    color: "Blanco",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Baja Silueta",
    climateType: "Frío/Calor",
    features: ["Perfil Bajo", "Bajo Ruido", "Frío Calor por Bomba"],
    image: "/3 TR FRIO CALOR MONOFASICO BAJO SILUETA TRADICIONAL.jpg",
    category: "commercial",
  },
  {
    id: "bs-trad-5",
    name: "Baja Silueta 5TR Trifásico",
    model: "53NQHE057A-701",
    type: "Baja Silueta",
    frigorias: 15000,
    kcal: 15000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 46kg / Cond: 67kg",
    dimensions: "Int: 120 x 30 x 87,4 cm | Ext: 90 x 117 x 35 cm",
    color: "Blanco",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Baja Silueta",
    climateType: "Frío/Calor",
    features: ["Trifásico", "Alta Capacidad", "Frío Calor por Bomba"],
    image: "/5 TR FRIO CALOR TRIFASICO BAJA SILUETA TRADICIONAL.jpg",
    category: "commercial",
  },
  {
    id: "bs-trad-6",
    name: "Baja Silueta 6TR Trifásico",
    model: "N3NQHE072-701",
    type: "Baja Silueta",
    frigorias: 18000,
    kcal: 18000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 46kg / Cond: 98kg",
    dimensions: "Int: 120 x 30 x 87,4 cm | Ext: 90 x 117 x 35 cm",
    color: "Blanco",
    isInverter: false,
    hasWifi: false,
    hasTimer: true,
    placement: "Baja Silueta",
    climateType: "Frío/Calor",
    features: ["Trifásico", "Máxima Capacidad", "Frío Calor por Bomba"],
    image: "/6 TR FRIO CALOR TRIFASICO BAJA SILUETA TRADICIONAL.jpg",
    category: "commercial",
  },

  // --- COMERCIAL: BAJA SILUETA INVERTER ---
  {
    id: "bs-inv-3",
    name: "Baja Silueta Inverter 3TR",
    model: "53NQHVO36A-901",
    type: "Baja Silueta",
    frigorias: 9000,
    kcal: 9000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 35kg / Cond: 67kg",
    dimensions: "Int: 110 x 24,9 x 77,4 cm | Ext: 109 x 81 x 50 cm",
    color: "Blanco",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Baja Silueta",
    climateType: "Frío/Calor",
    features: ["Inverter", "Wi-Fi", "Ahorro Energético", "Frío Calor por Bomba"],
    image: "/3 TR FRIO CALOR TRIFASICO BAJA SILUETA INVERTER.jpg",
    category: "commercial",
  },
  {
    id: "bs-inv-5",
    name: "Baja Silueta Inverter 5TR",
    model: "N3NQHV057A-901",
    type: "Baja Silueta",
    frigorias: 15000,
    kcal: 15000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 47kg / Cond: 74,5kg",
    dimensions: "Int: 120 x 30 x 87,4 cm | Ext: 94,6 x 81 x 41 cm",
    color: "Blanco",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Baja Silueta",
    climateType: "Frío/Calor",
    features: ["Inverter", "Wi-Fi", "Alta Eficiencia", "Frío Calor por Bomba"],
    image: "/5 TR FRIO CALOR TRIFASICO BAJA SILUETA INVERTER.jpg",
    category: "commercial",
  },
  {
    id: "bs-inv-6",
    name: "Baja Silueta Inverter 6TR",
    model: "53NQHV072A-901",
    type: "Baja Silueta",
    frigorias: 18000,
    kcal: 18000,
    voltage: "220 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 47kg / Cond: 94kg",
    dimensions: "Int: 120 x 30 x 87,4 cm | Ext: 95,2 x 133,3 x 41,5 cm",
    color: "Blanco",
    isInverter: true,
    hasWifi: true,
    hasTimer: true,
    placement: "Baja Silueta",
    climateType: "Frío/Calor",
    features: ["Inverter", "Wi-Fi", "Máximo Rendimiento", "Frío Calor por Bomba"],
    image: "/6 TR FRIO CALOR TRIFASICO BAJA SILUETA INVERTER.jpg",
    category: "commercial",
  },

  // --- CONDUCTOS SEPARADOS ---
  {
    id: "cond-sep-5",
    name: "Sistema Conductos 5TR",
    model: "53TQVC057-901",
    type: "Conductos",
    frigorias: 15000,
    kcal: 15000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 77kg / Cond: 97kg",
    dimensions: "Int: 56 x 138,5 x 61 cm | Ext: 71 x 75,9 x 71 cm",
    color: "Blanco",
    isInverter: false,
    hasTimer: true,
    placement: "Sistema Separado",
    climateType: "Frío/Calor",
    features: ["Compresor Scroll", "Protección de Fase", "Trifásico", "Frío Calor por Bomba"],
    image: "/5 TR FRIO CALOR TRIFASICO SISTEMA SEPARADO.jpg",
    category: "commercial",
  },
  {
    id: "cond-sep-6",
    name: "Sistema Conductos 6TR",
    model: "53TQVC072-901",
    type: "Conductos",
    frigorias: 18000,
    kcal: 18000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    weight: "Evap: 82kg / Cond: 115kg",
    color: "Blanco",
    isInverter: false,
    hasTimer: true,
    placement: "Sistema Separado",
    climateType: "Frío/Calor",
    features: ["Compresor Scroll", "Alta Durabilidad", "Trifásico", "Frío Calor por Bomba"],
    image: "/6 TR FRIO CALOR TRIFASICO SISTEMAS SEPARADOS.jpg",
    category: "commercial",
  },
  {
    id: "cond-sep-7.5",
    name: "Sistema Conductos 7.5TR",
    model: "53TQVC090-901",
    type: "Conductos",
    frigorias: 23500,
    kcal: 23500,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    isInverter: false,
    hasTimer: true,
    placement: "Sistema Separado",
    climateType: "Frío/Calor",
    features: ["Gran Capacidad", "Bajo Nivel Sonoro", "Trifásico", "Frío Calor por Bomba"],
    image: "/7,5 FRIO CALOR TRIFASICO SISTEMAS SEPARADOS.jpg",
    category: "commercial",
  },
  {
    id: "cond-sep-10",
    name: "Sistema Conductos 10TR",
    model: "53TQVC120-901",
    type: "Conductos",
    frigorias: 30000,
    kcal: 30000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    isInverter: false,
    hasTimer: true,
    placement: "Sistema Separado",
    climateType: "Frío/Calor",
    features: ["Industrial", "Compresor Scroll", "Trifásico", "Frío Calor por Bomba"],
    image: "/10 TR FRIO CALOR TRIFASICO SISTEMAS SEPARADOS.jpg",
    category: "commercial",
  },
  {
    id: "cond-sep-12.5",
    name: "Sistema Conductos 12.5TR",
    model: "53TQVC150-901",
    type: "Conductos",
    frigorias: 37500,
    kcal: 37500,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    isInverter: false,
    hasTimer: true,
    placement: "Sistema Separado",
    climateType: "Frío/Calor",
    features: ["Industrial", "Máxima Potencia", "Trifásico", "Frío Calor por Bomba"],
    image: "/12,5 TR FRIO CALOR TRIFASICO SISTEMAS SEPARADOS.jpg",
    category: "commercial",
  },

  // --- CALEFACTORES ---
  {
    id: "calefactor-100",
    name: "Calefactor a Gas 24.000 Kcal",
    model: "58MVP100-F-1-20",
    type: "Calefactor",
    frigorias: 0,
    kcal: 24444,
    voltage: "220 V",
    power: "Gas Natural / Envasado",
    efficiency: "93%",
    placement: "Conductos",
    climateType: "Calefacción",
    features: ["Eficiencia 93%", "Multiposición", "Ignición Superficie Caliente"],
    image: "/Calefactor a Gas para Conductos.jpg",
    category: "commercial",
  },
  {
    id: "calefactor-120",
    name: "Calefactor a Gas 29.000 Kcal",
    model: "58MVP120-F-1-20",
    type: "Calefactor",
    frigorias: 0,
    kcal: 29484,
    voltage: "220 V",
    power: "Gas Natural / Envasado",
    efficiency: "93.6%",
    placement: "Conductos",
    climateType: "Calefacción",
    features: ["Eficiencia 93.6%", "Ignición Superficie Caliente", "Multiposición"],
    image: "/Calefactor a Gas para Conductos.jpg",
    category: "commercial",
  },
  {
    id: "calefactor-140",
    name: "Calefactor a Gas 34.000 Kcal",
    model: "58MVP140-F-1-20",
    type: "Calefactor",
    frigorias: 0,
    kcal: 34020,
    voltage: "220 V",
    power: "Gas Natural / Envasado",
    efficiency: "93.5%",
    placement: "Conductos",
    climateType: "Calefacción",
    features: ["Eficiencia 93.5%", "Alta Potencia", "Multiposición"],
    image: "/Calefactor a Gas para Conductos.jpg",
    category: "commercial",
  },

  // --- ROOFTOP ---
  {
    id: "rooftop-eco-5",
    name: "Rooftop Ecológico 5TR",
    model: "50ZC-060",
    type: "Rooftop",
    frigorias: 15000,
    kcal: 15000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-407C",
    color: "Gris",
    isInverter: false,
    placement: "Techo",
    climateType: "Frío/Calor",
    features: ["Calefactor a Gas Integrado", "Compresor Scroll", "Trifásico", "Instalación Exterior"],
    image: "/5 TR FRIO CALOR TRIFASICO ROOFTOP ECOLOGICO.jpg",
    category: "commercial",
  },
  {
    id: "rooftop-eco-6",
    name: "Rooftop Ecológico 6TR",
    model: "50ZC-072",
    type: "Rooftop",
    frigorias: 18000,
    kcal: 18000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-407C",
    color: "Gris",
    isInverter: false,
    placement: "Techo",
    climateType: "Frío/Calor",
    features: ["Calefactor a Gas Integrado", "Exterior", "Trifásico"],
    image: "/20 TR FRIO CALOR ROOFTOP ECOLOGICO.jpg",
    category: "commercial",
  },
  {
    id: "rooftop-wm-10",
    name: "Rooftop Weathermaker 10TR",
    model: "48TC-D120---9",
    type: "Rooftop",
    frigorias: 30000,
    kcal: 30000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Gris",
    isInverter: false,
    placement: "Techo",
    climateType: "Frío Solo",
    features: ["Certificación LEED", "Alta Eficiencia", "Trifásico", "Gas Ecológico R-410A"],
    image: "/10 TR FRIO SOLO TRIFASICO ROOFTOP WEATHERMAKER.jpg",
    category: "commercial",
  },
  {
    id: "rooftop-wm-20",
    name: "Rooftop Weathermaker 20TR",
    model: "48TC-D240---9",
    type: "Rooftop",
    frigorias: 60000,
    kcal: 60000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Gris",
    isInverter: false,
    placement: "Techo",
    climateType: "Frío/Calor",
    features: ["Certificación LEED", "Doble Circuito", "Trifásico", "Gas Ecológico R-410A"],
    image: "/10 TR FRIO SOLO TRIFASICO ROOFTOP WEATHERMAKER.jpg",
    category: "commercial",
  },
  {
    id: "rooftop-midea-8.5",
    name: "Midea Rooftop 8.5TR",
    model: "MRC-102",
    type: "Rooftop",
    frigorias: 25500,
    kcal: 25500,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    isInverter: false,
    placement: "Techo",
    climateType: "Frío/Calor",
    features: ["Instalación Simple", "Compresor Scroll Eficiente", "Trifásico"],
    image: "/8,5 TR FRIO CALOR MIDEA ROOFTOP.jpg",
    category: "commercial",
  },
  {
    id: "rooftop-midea-20",
    name: "Midea Rooftop 20TR",
    model: "MRC-240",
    type: "Rooftop",
    frigorias: 60000,
    kcal: 60000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Blanco",
    isInverter: false,
    placement: "Techo",
    climateType: "Frío/Calor",
    features: ["Gran Capacidad", "Industrial", "Trifásico"],
    image: "/8,5 TR FRIO CALOR MIDEA ROOFTOP.jpg",
    category: "commercial",
  },

  // --- CHILLER ---
  {
    id: "chiller-6",
    name: "Chiller 6TR Trifásico",
    model: "30RBS-070",
    type: "Chiller",
    frigorias: 18000,
    kcal: 18000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Gris",
    isInverter: false,
    placement: "Exterior",
    climateType: "Frío/Calor",
    features: ["Control Táctil", "Módulo Hidrónico", "Trifásico", "Gas Ecológico R-410A"],
    image: "/6 TR TRIFASICO CHILLER.jpg",
    category: "commercial",
  },
  {
    id: "chiller-10",
    name: "Chiller 10TR Trifásico",
    model: "30RBS-120",
    type: "Chiller",
    frigorias: 30000,
    kcal: 30000,
    voltage: "380 V (50 hz)",
    refrigerant: "R-410A",
    color: "Gris",
    isInverter: false,
    placement: "Exterior",
    climateType: "Frío/Calor",
    features: ["Alta Eficiencia", "Bajo Ruido", "Trifásico", "Gas Ecológico R-410A"],
    image: "/6 TR TRIFASICO CHILLER.jpg",
    category: "commercial",
  },
];

export const SERVICES: ServiceItem[] = [
  {
    title: "Venta e Instalación",
    description: "Comercialización y montaje de equipos individuales, centrales, fan-coil y chillers.",
    iconName: "ShoppingCart"
  },
  {
    title: "Mantenimiento Preventivo",
    description: "Planes a medida para empresas, consorcios y particulares. Limpieza de conductos y filtros.",
    iconName: "Wrench"
  },
  {
    title: "Proyectos y Balances",
    description: "Cálculo de balance térmico, asesoramiento profesional y diseño de sistemas de ventilación.",
    iconName: "ClipboardCheck"
  },
  {
    title: "Obras de Envergadura",
    description: "Especialistas en grandes superficies, laboratorios, centros de cómputos y plantas industriales.",
    iconName: "Building2"
  }
];